name: CI

on:
  push:
    branches: [ master ]
    
env: 
  BUCKET: mercadoteste.loja.website  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      
      - name: Install Dependencies
        run: yarn install
        
      # Testes
      
      - name: Build
        run: yarn build
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SAKEY }}
          export_default_credentials: true
      
      - name: Upload files to bucket
        run: gsutil -m rsync -R ./build gs://"$BUCKET"
      
      - name: Allow AllUsers
        run: gsutil -m acl ch -R -u AllUsers:R gs://"$BUCKET"
      
      - name: Set Cache-Control
        run: gsutil -m setmeta -h "Cache-Control:public, max-age=15768000" gs://"$BUCKET"/**/*.{png,svg,css,js}
        
      - name: Set Cache-Control
        run: gsutil setmeta -h "Cache-Control:nocache, no-store" gs://"$BUCKET"/index.html
        
      
        

